version: '3'
services:

  ### Cameras ###

  axis-1:
    build:
      context: vidgear-recorder
    volumes:
      - /media/sealog/platform_landkrabba:/app/recordings
    environment:
      - SOURCE=rtsp://192.168.1.100/axis-media/media.amp?camera=1
      - SINK_SUFFIX=axis1.mp4
      - SINK_COMPRESSION=False
      - VERBOSE=True

  axis-2:
    build:
      context: vidgear-recorder
    volumes:
      - /media/sealog/platform_landkrabba:/app/recordings
    environment:
      - SOURCE=rtsp://192.168.1.100/axis-media/media.amp?camera=2
      - SINK_SUFFIX=axis2.mp4
      - SINK_COMPRESSION=False
      - VERBOSE=True

  axis-3:
    build:
      context: vidgear-recorder
    volumes:
      - /media/sealog/platform_landkrabba:/app/recordings
    environment:
      - SOURCE=rtsp://192.168.1.100/axis-media/media.amp?camera=3
      - SINK_SUFFIX=axis3.mp4
      - SINK_COMPRESSION=False
      - VERBOSE=True

  axis-4:
    build:
      context: vidgear-recorder
    volumes:
      - /media/sealog/platform_landkrabba:/app/recordings
    environment:
      - SOURCE=rtsp://192.168.1.100/axis-media/media.amp?camera=4
      - SINK_SUFFIX=axis4.mp4
      - SINK_COMPRESSION=False
      - VERBOSE=True
