version: '3'
services:

  ### Cameras ###

  ### Camera 1
  camera-rtp-1:
    image: chalmersrevere/opendlv-device-camera-rtp-amd64:v0.0.6
    restart: unless-stopped
    ipc: "host"
    volumes:
      - /tmp:/tmp
    command: "--url=rtsp://192.168.1.100/axis-media/media.amp?camera=1 --cid=120
      --name=rtp1. --remote" # --remote has the side effect of not recording anything locally unless a remote command is issued
