version: '3'
services:

  ### Setup for a single NAVICO radar (CID=121)
  navico-radar:
    image: opendlv-device-radar-navico:morise
    restart: unless-stopped
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    command: "--cid=121 --ip=236.6.7.5 --port=6878 --antenna_height=7
      --bearing_alignment=0 --gain=30 --interference_rejection=30
      --local_interference_rejection=30 --noise_rejection=30 --transmit_lock=0
      --rain_clutter=30 --range_alpha=1500 --range_bravo=1500 --scan_speed=3
      --sea_clutter=30 --side_lobe_suppression=0 --target_boost=3
      --target_expansion=3 --target_separation=3 --doppler=0"
