version: '3.9'

services:

  navico-radar:
    image: registry.opendlv.org/testing/opendlv-device-radar-navico:v0.1.2
    container_name: cw-radar
    restart: unless-stopped
    network_mode: "host"
    command: " --cid=112 --ip=236.6.7.5 --port=6878 --antenna_height=3 --bearing_alignment=345 --id=1201 --id_bravo=1202 --gain=36 --gain_bravo=50 --interference_rejection=1 --interference_rejection_bravo=1 --local_interference_rejection=1 --local_interference_rejection_bravo=1 --noise_rejection=1 --noise_rejection_bravo=1 --transmit_lock=0 --rain_clutter=0 --rain_clutter_bravo=0 --range=500 --range_bravo=5000 --scan_speed=3 --scan_speed_bravo=3 --sea_clutter=0 --sea_clutter_bravo=0 --side_lobe_suppression=0 --side_lobe_suppression_bravo=0 --target_boost=0 --target_boost_bravo=0 --sea_state=1 --sea_state_bravo=1 --target_expansion=0 --target_expansion_bravo=0 --target_separation=0 --target_separation_bravo=0 --doppler=0 --doppler_bravo=0 "

  keelson-opendlv2radar:
    image: ghcr.io/mo-rise/keelson:0.1.0-pre.16
    network_mode: host
    restart: always
    command: [ "opendlv2radar -r rise -e gota -i navico --cid 112" ]
