version: '3'
services:
  rec2csv_png:
    build:
      context: https://github.com/chalmers-revere/rec2csv-png.git
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/opt/data
    working_dir: /opt/data
    command: "--rec=recordings/2021-12-17_121016-_h264_rtp1.rec
      --odvd=opendlv.standard-message-set/opendlv.odvd"
