version: '3'
services:

  ouster-lidar:
    image: ghcr.io/mo-rise/crowsnest-connector-lidar-ouster:v0.1.1
    restart: unless-stopped
    network_mode: "host"
    environment:
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC_POINTCLOUD=CROWSNEST/LANDKRABBA/LIDAR/0/POINTCLOUD
      - OUSTER_HOSTNAME=10.10.20.100
      - OUSTER_ATTITUDE=0,0,0
      - POINTCLOUD_FREQUENCY=1
      - POINTCLOUD_SUBSET_SAMPLING=3
