version: '3'
services:

  navico-radar:
    image: registry.opendlv.org/testing/opendlv-device-radar-navico:v0.0.7
    restart: unless-stopped
    network_mode: "host"
    command: "--cid=112 --ip=236.6.7.5 --port=6878 --antenna_height=5000 --bearing_alignment=1396 --gain=15 --rain_clutter=0 --interference_rejection=1 --local_interference_rejection=1 --noise_rejection=1 --transmit_lock=0 --range_alpha=1000 --range_bravo=1000 --scan_speed=3 --sea_clutter=40 --side_lobe_suppression=40 --target_boost=1 --target_expansion=1 --target_separation=1 --doppler=0 --verbose"

  crowsnest-processor-radar:
    image: ghcr.io/mo-rise/crowsnest-processor-opendlv-radar:v0.1.2
    restart: unless-stopped
    network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 1024M
    environment:
      - CLUON_CID=112
      - MQTT_BROKER_HOST=localhost
      - MQTT_BROKER_PORT=1883
      - MQTT_BASE_TOPIC=CROWSNEST/LANDKRABBA/RADAR/0/SWEEP
      - RADAR_MIN_READING_WEIGHT=0
      - RADAR_SWEEP_ANGULAR_SUBSETTING=2
      - RADAR_SWEEP_RADIAL_SUBSETTING=2
      