version: '3'
services:
  rec2csv_png:
    build:
      context: https://github.com/chalmers-revere/rec2csv-png.git
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/opt/data
    working_dir: /opt/data
    command: "--rec=<path_to_file.rec> --odvd=opendlv.standard-message-set/opendlv.odvd"
