network:
    version: 2
    renderer: networkd
    ethernets:
        enp1s0:
            addresses:
             - 10.10.7.1/24  # For access to AXIS camera at 10.10.7.61
            dhcp4: no
        enp2s0:
            addresses:
             - 10.10.20.1/24
            dhcp4: no
            routes:
             - to: 236.6.7.0/24
               scope: link
        enp3s0:
            addresses:
             - 10.10.30.1/24
             - 192.168.4.0/24  # For access to YDEN gateway at 192.168.4.1
            dhcp4: no
        enp4s0:
            addresses:
             - 10.10.40.1/24
            dhcp4: no
        enp5s0:
            dhcp4: yes
            dhcp4-overrides:
                route-metric: 2
        enp6s0:
            dhcp4: yes
            dhcp4-overrides:
                route-metric: 1
